# Start with a lightweight Node.js Alpine base
FROM node:20-alpine

# Install Java JRE (required for Firebase Emulators) and bash
RUN apk add --no-cache openjdk21-jre bash

# Install the Firebase CLI globally
RUN npm install -g firebase-tools

# Copy firebase.json and .firebase.json to the container
COPY docker/firebase.json ./

# Set the working directory inside the container
WORKDIR /home/node/app

# CRUCIAL: Baixa a UI do emulador durante o build da imagem
RUN firebase setup:emulators:ui

# Expose essential emulator ports (Adjust based on what you use)
# 4000: Emulator UI | 8080: Firestore | 9099: Auth | 9199: Storage | 5001: Functions
EXPOSE 4000 8080 9099 9199 5001

# Command to start the emulator pointing to the workspace configuration
CMD ["firebase", "emulators:start", "--only", "auth", "--import=./data", "--export-on-exit"]
